// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:nscgschedule/models/friend_models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FriendAdapter());
    registerAdapter(FriendDayScheduleAdapter());
    registerAdapter(FriendExamAdapter());
    registerAdapter(FriendLessonAdapter());
    registerAdapter(FriendTimetableAdapter());
    registerAdapter(PrivacyLevelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FriendAdapter());
    registerAdapter(FriendDayScheduleAdapter());
    registerAdapter(FriendExamAdapter());
    registerAdapter(FriendLessonAdapter());
    registerAdapter(FriendTimetableAdapter());
    registerAdapter(PrivacyLevelAdapter());
  }
}
